name: 'Build latest commit'

on:
  push:
    branches: [ 'master' ]

jobs:
  build-tauri:
    strategy:
      fail-fast: true
      matrix:
        platform: [windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: ⚡ Set short SHA ENV
        run: echo "SHORT_SHA=$("${{ github.sha }}".SubString(0, 8))" >> $env:GITHUB_ENV

      - name: ⏬ Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: ⚡ Set up cargo cache
        uses: actions/cache@v4
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            src-tauri/target/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo

      - name: ⏬ Setup node version
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: ⏬ Enable corepack and install
        run: corepack enable && corepack install

      - name: 📥 Install Node Dependencies
        run: yarn install --frozen-lockfile 

      - name: 🔨 Build
        run: yarn tauri build

      - name: Rename soundcoremanager.exe
        if: matrix.platform == 'windows-latest'
        run: ren target\release\deps\soundcoremanager.exe SoundcoreManager-${{ matrix.platform }}-${{ env.SHORT_SHA }}.exe

      - name: ⏫ Upload Build Artifact
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: SoundcoreManager-${{ matrix.platform }}.exe
          path: target\release\deps\SoundcoreManager-${{ matrix.platform }}-${{ env.SHORT_SHA }}.exe
